### ISSUE TITLE
Hot Tub

### ISSUE THREAD

**Issue by mmmmmmorten** [smariotti/TrophyHuntMod#2]
Saga mode and using it for cool features and collecting all trophies...  not really 4 h run :)
Hot Tub consumes wood at same speed as windmill and Spinning wheel does..  almost instant, thus there is no comfort from Hot Tub as it needs to be on (with wood) to do that...
Saw your mod detected other mods...  might as well disable 4h countdown if other mods are present?

Love the mod.  instant melting ore, faster farm, random drops, faster sailing .. what's not to like :)

Only sad thing is trophy stats on bar is only per session....  so if I save, quit and log in again that is lost.. thus no stats /sad
Total score and deaths are kept so that's cool...

M

**Comment by smariotti** [comment]
Yeah, the mod persists no data outside of the session. That's something I may change.

Never thought much about the hot tub since that's a late game decoration and isn't conducive to "collect as many points as you can in four hours" which is the main purpose of the mod.

I would consider opening it up to more casual play like completing the run in multiple sessions. The focus so far is on going in blind (no map scouting or using the map viewer on the seed) and competing in real time against other players.

Saga mode might be fun for casual play, and maybe deserves to spin off into its own mod that persists data between sessions.

Thanks for your thoughts!

**Comment by smariotti** [comment]
Ok, version 0.6.7 should fix the hot tub issue in Trophy Saga mode. Thanks for the bug report, Morten!
